import { Task, AppSettings } from '@/types/task';

const now = new Date();
const dayOffset = (d: number) => {
  const dt = new Date(now);
  dt.setDate(dt.getDate() + d);
  return dt.toISOString();
};

export const SCREENSHOT_SETTINGS: AppSettings = {
  animationsEnabled: true,
  remindersEnabled: true,
  defaultFilter: 'All',
  defaultSort: 'Priority',
  workDuration: 25,
  soundEnabled: true,
  volume: 100,
  workSound: 'Classic Bell',
  shortBreakSound: 'Digital Beep',
  longBreakSound: 'Soft Chime',
};

export const SCREENSHOT_TASKS: Task[] = [
  // 18 completed
  { id: 's1', title: 'Morning workout routine', description: '30 min cardio + stretching', dueDate: dayOffset(-14), createdAt: dayOffset(-20), lastEdited: dayOffset(-14), priority: 'High', category: 'Health', isCompleted: true, isPinned: false, isImportant: true, isArchived: false, reminderEnabled: true, estimatedDuration: '45m', subtasks: [], recurringInterval: 'Daily', dependencies: [], isTemplate: false, pomodoroSessions: 12 },
  { id: 's2', title: 'Review quarterly report', description: 'Check financials and KPIs', dueDate: dayOffset(-12), createdAt: dayOffset(-18), lastEdited: dayOffset(-12), priority: 'Urgent', category: 'Work', isCompleted: true, isPinned: true, isImportant: true, isArchived: false, reminderEnabled: true, estimatedDuration: '2h', subtasks: [], recurringInterval: 'None', dependencies: [], isTemplate: false, pomodoroSessions: 8 },
  { id: 's3', title: 'Grocery shopping', description: 'Milk, eggs, vegetables, coffee', dueDate: dayOffset(-10), createdAt: dayOffset(-12), lastEdited: dayOffset(-10), priority: 'Medium', category: 'Shopping', isCompleted: true, isPinned: false, isImportant: false, isArchived: false, reminderEnabled: false, estimatedDuration: '1h', subtasks: [], recurringInterval: 'Weekly', dependencies: [], isTemplate: false, pomodoroSessions: 0 },
  { id: 's4', title: 'Read 20 pages of book', description: 'Atomic Habits chapter 4', dueDate: dayOffset(-9), createdAt: dayOffset(-11), lastEdited: dayOffset(-9), priority: 'Low', category: 'Personal', isCompleted: true, isPinned: false, isImportant: false, isArchived: false, reminderEnabled: false, estimatedDuration: '30m', subtasks: [], recurringInterval: 'Daily', dependencies: [], isTemplate: false, pomodoroSessions: 2 },
  { id: 's5', title: 'Team standup meeting', description: 'Sync with engineering team', dueDate: dayOffset(-8), createdAt: dayOffset(-10), lastEdited: dayOffset(-8), priority: 'High', category: 'Work', isCompleted: true, isPinned: false, isImportant: true, isArchived: false, reminderEnabled: true, estimatedDuration: '15m', subtasks: [], recurringInterval: 'Daily', dependencies: [], isTemplate: false, pomodoroSessions: 1 },
  { id: 's6', title: 'Pay electricity bill', description: 'Due before the 15th', dueDate: dayOffset(-7), createdAt: dayOffset(-9), lastEdited: dayOffset(-7), priority: 'Urgent', category: 'Finance', isCompleted: true, isPinned: false, isImportant: false, isArchived: false, reminderEnabled: true, estimatedDuration: '10m', subtasks: [], recurringInterval: 'Monthly', dependencies: [], isTemplate: false, pomodoroSessions: 0 },
  { id: 's7', title: 'Doctor appointment', description: 'Annual checkup at 2pm', dueDate: dayOffset(-6), createdAt: dayOffset(-20), lastEdited: dayOffset(-6), priority: 'High', category: 'Health', isCompleted: true, isPinned: true, isImportant: true, isArchived: false, reminderEnabled: true, estimatedDuration: '1h', subtasks: [], recurringInterval: 'None', dependencies: [], isTemplate: false, pomodoroSessions: 0 },
  { id: 's8', title: 'Submit assignment', description: 'Math homework chapter 3', dueDate: dayOffset(-5), createdAt: dayOffset(-8), lastEdited: dayOffset(-5), priority: 'Medium', category: 'School', isCompleted: true, isPinned: false, isImportant: false, isArchived: false, reminderEnabled: false, estimatedDuration: '1h', subtasks: [], recurringInterval: 'None', dependencies: [], isTemplate: false, pomodoroSessions: 3 },
  { id: 's9', title: 'Plan weekend trip', description: 'Research cabins near lake', dueDate: dayOffset(-4), createdAt: dayOffset(-7), lastEdited: dayOffset(-4), priority: 'Low', category: 'Personal', isCompleted: true, isPinned: false, isImportant: false, isArchived: false, reminderEnabled: false, estimatedDuration: '45m', subtasks: [], recurringInterval: 'None', dependencies: [], isTemplate: false, pomodoroSessions: 0 },
  { id: 's10', title: 'Clean workspace', description: 'Organize desk and files', dueDate: dayOffset(-3), createdAt: dayOffset(-5), lastEdited: dayOffset(-3), priority: 'Medium', category: 'Personal', isCompleted: true, isPinned: false, isImportant: false, isArchived: false, reminderEnabled: false, estimatedDuration: '30m', subtasks: [], recurringInterval: 'Weekly', dependencies: [], isTemplate: false, pomodoroSessions: 0 },
  { id: 's11', title: 'Call mom', description: 'Weekly Sunday call', dueDate: dayOffset(-2), createdAt: dayOffset(-4), lastEdited: dayOffset(-2), priority: 'Medium', category: 'Personal', isCompleted: true, isPinned: false, isImportant: true, isArchived: false, reminderEnabled: true, estimatedDuration: '20m', subtasks: [], recurringInterval: 'Weekly', dependencies: [], isTemplate: false, pomodoroSessions: 0 },
  { id: 's12', title: 'Update portfolio site', description: 'Add recent projects', dueDate: dayOffset(-2), createdAt: dayOffset(-6), lastEdited: dayOffset(-2), priority: 'Low', category: 'Other', isCompleted: true, isPinned: false, isImportant: false, isArchived: false, reminderEnabled: false, estimatedDuration: '2h', subtasks: [], recurringInterval: 'None', dependencies: [], isTemplate: false, pomodoroSessions: 5 },
  { id: 's13', title: 'Meal prep for week', description: 'Cook lunches in batch', dueDate: dayOffset(-1), createdAt: dayOffset(-3), lastEdited: dayOffset(-1), priority: 'Medium', category: 'Health', isCompleted: true, isPinned: false, isImportant: false, isArchived: false, reminderEnabled: false, estimatedDuration: '1h', subtasks: [], recurringInterval: 'Weekly', dependencies: [], isTemplate: false, pomodoroSessions: 0 },
  { id: 's14', title: 'Backup photos', description: 'To external drive', dueDate: dayOffset(-1), createdAt: dayOffset(-2), lastEdited: dayOffset(-1), priority: 'Low', category: 'Other', isCompleted: true, isPinned: false, isImportant: false, isArchived: false, reminderEnabled: false, estimatedDuration: '30m', subtasks: [], recurringInterval: 'Monthly', dependencies: [], isTemplate: false, pomodoroSessions: 0 },
  { id: 's15', title: 'Review pull requests', description: '3 PRs awaiting review', dueDate: dayOffset(0), createdAt: dayOffset(-1), lastEdited: dayOffset(0), priority: 'High', category: 'Work', isCompleted: true, isPinned: false, isImportant: true, isArchived: false, reminderEnabled: true, estimatedDuration: '40m', subtasks: [], recurringInterval: 'None', dependencies: [], isTemplate: false, pomodoroSessions: 4 },
  { id: 's16', title: 'Water plants', description: 'Living room and balcony', dueDate: dayOffset(0), createdAt: dayOffset(-1), lastEdited: dayOffset(0), priority: 'Low', category: 'Personal', isCompleted: true, isPinned: false, isImportant: false, isArchived: false, reminderEnabled: false, estimatedDuration: '15m', subtasks: [], recurringInterval: 'Weekly', dependencies: [], isTemplate: false, pomodoroSessions: 0 },
  { id: 's17', title: 'Listen to podcast', description: 'Productivity episode', dueDate: dayOffset(0), createdAt: dayOffset(-1), lastEdited: dayOffset(0), priority: 'Low', category: 'Personal', isCompleted: true, isPinned: false, isImportant: false, isArchived: false, reminderEnabled: false, estimatedDuration: '45m', subtasks: [], recurringInterval: 'None', dependencies: [], isTemplate: false, pomodoroSessions: 0 },
  { id: 's18', title: 'Evening meditation', description: '10 min breathing', dueDate: dayOffset(0), createdAt: dayOffset(-1), lastEdited: dayOffset(0), priority: 'Medium', category: 'Health', isCompleted: true, isPinned: false, isImportant: false, isArchived: false, reminderEnabled: false, estimatedDuration: '10m', subtasks: [], recurringInterval: 'Daily', dependencies: [], isTemplate: false, pomodoroSessions: 1 },

  // 5 pending
  { id: 's19', title: 'Prepare presentation deck', description: 'Quarterly business review', dueDate: dayOffset(1), createdAt: dayOffset(0), lastEdited: dayOffset(0), priority: 'Urgent', category: 'Work', isCompleted: false, isPinned: true, isImportant: true, isArchived: false, reminderEnabled: true, estimatedDuration: '3h', subtasks: [{ id: 'st1', title: 'Outline slides', isCompleted: true }, { id: 'st2', title: 'Design visuals', isCompleted: false }, { id: 'st3', title: 'Rehearse', isCompleted: false }], recurringInterval: 'None', dependencies: [], isTemplate: false, pomodoroSessions: 6 },
  { id: 's20', title: 'Dentist appointment', description: 'Cleaning at 10am', dueDate: dayOffset(2), createdAt: dayOffset(-3), lastEdited: dayOffset(-3), priority: 'High', category: 'Health', isCompleted: false, isPinned: false, isImportant: true, isArchived: false, reminderEnabled: true, estimatedDuration: '1h', subtasks: [], recurringInterval: 'None', dependencies: [], isTemplate: false, pomodoroSessions: 0 },
  { id: 's21', title: 'Finish online course', description: 'Complete module 5', dueDate: dayOffset(3), createdAt: dayOffset(-5), lastEdited: dayOffset(-2), priority: 'Medium', category: 'School', isCompleted: false, isPinned: false, isImportant: false, isArchived: false, reminderEnabled: false, estimatedDuration: '2h', subtasks: [], recurringInterval: 'None', dependencies: [], isTemplate: false, pomodoroSessions: 3 },
  { id: 's22', title: 'Renew car insurance', description: 'Compare 3 providers', dueDate: dayOffset(4), createdAt: dayOffset(-1), lastEdited: dayOffset(-1), priority: 'Medium', category: 'Finance', isCompleted: false, isPinned: false, isImportant: false, isArchived: false, reminderEnabled: true, estimatedDuration: '30m', subtasks: [], recurringInterval: 'None', dependencies: [], isTemplate: false, pomodoroSessions: 0 },
  { id: 's23', title: 'Book flight tickets', description: 'Summer vacation planning', dueDate: dayOffset(6), createdAt: dayOffset(0), lastEdited: dayOffset(0), priority: 'Low', category: 'Personal', isCompleted: false, isPinned: false, isImportant: false, isArchived: false, reminderEnabled: false, estimatedDuration: '1h', subtasks: [], recurringInterval: 'None', dependencies: [], isTemplate: false, pomodoroSessions: 0 },
];

export const SCREENSHOT_STREAK = 15;
export const SCREENSHOT_COMPLETION = 92;